package com.lulobank.clients.services.utils;

public enum StatusClientVerificationFirebaseEnum {
  CREATED,
  IN_PROGRESS,
  OK,
  KO_BLACKLIST_MEDIUM_RISK,
  KO_BLACKLIST_HIGH_RISK,
  KO_IDENTITY,
  KO_IDENTITY_FRAUD,
  KO_ALREADY_CLIENT_EXISTS,
  FAILED,
  BLACKLIST_FAILED,
  KO_DIGITAL_EVIDENCE,
  KO_ZENDESK_USER_CREATION,
  START_PEP_VALIDATION,
  KO_SAVINGS_ACCOUNT_CREATION
}
